Repository FromDoppler/doppler-menu-mfe, pull requests merged in 2024-08, with the labels that each got.

#575 [DOI-1533] Move user selection modal to app component
  src/App.test.tsx
  src/App.tsx
  src/components/UserMenu.tsx
  src/components/UserSelection.tsx
Labels: size/M

#578 [DAT-2136] - fix issue with stepper
  src/components/LandingPlan.tsx
  src/components/UserPlan.test.tsx
  src/components/UserPlan.tsx
Labels: size/XS

#579 [DOI-1557] Fix issue when restarting session on doppler legacy
  src/components/UserSelection.tsx
Labels: size/S
