Repository FromDoppler/doppler-menu-mfe, pull requests merged in 2025-01, with the labels that each got.

#616 Add userpilot logs
  src/App.tsx
Labels: size/XS

#617 Add mfe logs
  src/index.tsx
Labels: size/XS

#618 Support multiple environments
  .env
  .env.development
  .env.int
  .env.production
  .env.qa
  Dockerfile
  build-n-publish.sh
  doppler-jenkins-ci.groovy
  package.json
  src/AppConfiguration.tsx
  src/index.tsx
  yarn.lock
Labels: size/M

#622 Remove userpilot logs
  src/App.tsx
  src/index.tsx
Labels: size/XS

#623 [DAT-2335] Add user props
  src/App.tsx
Labels: size/S

#615 [DAT-2268] - Add buy onsite in the user menu
  src/components/Header.test.tsx
  src/components/MenuRight.test.tsx
  src/components/OnSitePlan.test.tsx
  src/components/OnSitePlan.tsx
  src/components/UserMenu.test.tsx
  src/components/UserPlan.test.tsx
  src/components/UserPlan.tsx
  src/mocks/userMock.ts
  src/utils.ts
Labels: size/L

#624 Fix active addons prop
  src/App.tsx
  src/utils.ts
Labels: size/S

#628 Dat 2352
  src/App.tsx
  src/hooks/useUserpilot.tsx
  src/model.ts
Labels: size/L

#629 Send user account id to userpilot
  src/hooks/useUserpilot.tsx
  src/model.ts
Labels: size/XS
